/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   child_process.c                                    :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: mvillarr <mvillarr@student.42lausanne.ch>  +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2023/07/31 10:39:49 by mvillarr          #+#    #+#             */
/*   Updated: 2023/08/12 16:33:36 by mvillarr         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "../../includes/minishell.h"

// This function is used to set the terminal attributes for the child process.
// It takes a pointer to a termios structure as an argument. The "tcsetattr"
// function is used to set the terminal attributes. The "TCSAFLUSH" option is
// used to change the attributes after all output has been processed.
// The sigint_child function is then called.

//void  child_signal(struct termios *mirror_termios)
//{
//  tcsetattr(1, TCSAFLUSH, mirror_termios);
//  sigint_child();
//}

// This function sets up the signal handling for the SIGINT signal (which is
// typically generated by the user pressing Ctrl+C). The sigaction structure is
// set up to specify that the default action should be taken when the signal is
// received (SIG_DFL), and that system calls should be restarted if possible
// after the signal is handled (SA_RESTART). The "sigemptyset" function is used
// to initialize the signal set to be empty, and sigaction is used to change
// the action taken by the process on receipt of the specific signal.

//void  sigint_child(void)
//{
//  struct sigaction  ctr_c;
//
//  ctr_c.sa_handler = SIG_DFL;
//  ctr_c.sa_flags = SA_RESTART;
//  sigemptyset(&ctr_c.sa_mask);
//  sigaction(SIGINT, &ctr_c, NULL);
//}

// ctr backslash*
// This function is similar to sigint_child, but it sets up the signal handling
// for the SIGQUIT signal (which is typically generated by the user pressing
// Ctrl+). The sigaction structure is set up in the same way as in sigint_child.

//void  ctr_bl_signal(void)
//{
//  struct sigaction ctr_bl;
//
//  ctr_bl.sa_handler = SIG_DFL;
//  ctr_bl.sa_flags = SA_RESTART;
//  sigemptyset(&ctr_bl.sa_mask);
//  sigaction(SIGQUIT, &ctr_bl, NULL);
//}

