/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   parent_process.c                                   :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: mvillarr <mvillarr@student.42lausanne.ch>  +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2023/07/31 10:39:31 by mvillarr          #+#    #+#             */
/*   Updated: 2023/07/31 10:59:34 by mvillarr         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "../../includes/minishell.h"

// This function is used to set up signal handling for the parent process.
// It calls two other functions: ctr_c_signal_parent and sigint_parent.
void	parent_signal(void)
{
	ctr_c_signal_parent();
        sigint_parent();
}

// This function is a signal handler for the SIGINT signal (which is typically
// generated by the user pressing Ctrl+C). It takes an integer as an argument,
// which is the signal number. If the signal number is SIGINT, it writes "^C\n"
// to the standard output, calls rl_on_new_line to move the cursor to a new
// line, and replaces the current line with an empty string using
// rl_replace_line. These last two functions are part of the readline library,
// which is used for handling input from the user.
void	sigint_parent(int signum)
{
	if (signum == SIGINT)
	{
		write(1, "^C\n", 3);
		rl_on_new_line();
		rl_replace_line("", 0):
	}
}

// This function sets up the signal handling for the SIGINT signal in the parent
// process. It creates a sigaction structure and sets the sa_handler field to
// sigint_parent, which means that the sigint_parent function will be called
// when the SIGINT signal is received. The sa_flags field is set to SA_RESTART,
// which means that if a system call is interrupted by the signal, it will be
// restarted. The sigemptyset function is used to initialize the signal set to
// be empty, and sigaction is used to change the action taken by the process on
// receipt of the specific signal.
void	ctr_c_signal_parent(void)
{
	struct sigaction	ctr_c;

	ctr_c.sa_handler = sigint_parent;
	ctr_c.sa_flags = SA_RESTART;
	sigemptyset(&ctr_c.sa_mask);
        sigaction(SIGINT, &ctr_c, NULL);
}

